// JavaScript Document
jQuery('#testimonial-carousel').owlCarousel({
loop:true,
margin:10,
nav:false,
dots:true,
responsive:{
    0:{
        items:1
    },
    768:{
        items:2
    },
    1200:{
        items:2
    },
    1366:{
        items:3
    },
}
});
jQuery('#inner-about-testimonials-owl').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        768:{
            items:1
        },
        1200:{
            items:1
        },
        1366:{
            items:1
        },
    }
    });
